### ISSUE TITLE
GeoIPS will not run when installed via `pip install .` without the "test" target

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#426]
# Requested Update

### Description
GeoIPS currently fails to run if installed by simply calling `pip install .`. It must, instead, be installed with `pip install .[test]`. This is because `pytest` is used in `geoips/plugin_registry.py` but is not included in the base GeoIPS installation requirements.

There are three reasonable solutions to this issue:
1. Include pytest in the requirements for base GeoIPS.
2. Only import pytest if it is available and raise an error if it is encountered but not imported.
3. Remove pytest from plugin_registry.py and move the tests into the unit_test directory.

Personally, I would prefer to keep unit tests out of the actual code base, but maybe there is a reason that I'm unaware of that requires the use of `pytest.xfail` in `plugin_registry.py` rather than in the external unit tests.

### Code to demonstrate issue
- In a fresh environment, install GeoIPS via `pip install .`
- Try calling `run_procflow -h`

You will see something like:
```
geoips_user@eae1915cc33f:/geoips$ cd ..
geoips_user@eae1915cc33f:/$ run_procflow -h
Traceback (most recent call last):
  File "/home/geoips_user/.local/bin/run_procflow", line 5, in <module>
    from geoips.commandline.run_procflow import main
  File "/home/geoips_user/.local/lib/python3.10/site-packages/geoips/__init__.py", line 31, in <module>
    from geoips import interfaces
  File "/home/geoips_user/.local/lib/python3.10/site-packages/geoips/interfaces/__init__.py", line 15, in <module>
    from geoips.interfaces.module_based.algorithms import algorithms
  File "/home/geoips_user/.local/lib/python3.10/site-packages/geoips/interfaces/module_based/algorithms.py", line 15, in <module>
    from geoips.interfaces.base import BaseModuleInterface
  File "/home/geoips_user/.local/lib/python3.10/site-packages/geoips/interfaces/base.py", line 297, in <module>
    class BaseInterface:
  File "/home/geoips_user/.local/lib/python3.10/site-packages/geoips/interfaces/base.py", line 309, in BaseInterface
    from geoips.plugin_registry import plugin_registry
  File "/home/geoips_user/.local/lib/python3.10/site-packages/geoips/plugin_registry.py", line 21, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

### Checklist for Completion
* [ ]

**Comment by evrose54** [comment]
The PluginRegistry class used pytest.xfail to validate the registry upon initialization. If the registry failed, it would require users to fix the associated problem before continuing to develop with GeoIPS. If we prefer to not validate the registry at initialization time, we can move the pytest functionality on to the test_plugin_registries module. I'll go ahead and start doing that to see if we prefer it over the current  implementation.
