### ISSUE TITLE
Plugins must be write accessible to the running user for create_plugin_registries to work

### ISSUE THREAD

**Issue by biosafetylvl5** [NRLMMD-GEOIPS/geoips#812]
# Requested Update

### Description
*  [ In 2-3 sentences briefly describe the required bug fix or feature with this issue. ]

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

```
geoips_user@1400017fafb0:/workspaces/geoips_clavrx$ create_plugin_registries 
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'boxdefinitions' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'interp_scipy' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'interp_pyresample' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'remss_reader' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'geostationary_geolocation' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'hrit_reader' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:821  INTERACTIVE: Skipping module 'tc_file_naming' from 'geoips', interface_name is 'None'
31_203251 create_plugin_registries.py:319  INTERACTIVE: Writing /app/geoips_packages/geoips/geoips/registered_plugins.json
Traceback (most recent call last):
  File "/home/geoips_user/.local/bin/create_plugin_registries", line 8, in <module>
    sys.exit(main())
  File "/app/geoips_packages/geoips/geoips/create_plugin_registries.py", line 946, in main
    create_plugin_registries(plugin_packages, save_type)
  File "/app/geoips_packages/geoips/geoips/create_plugin_registries.py", line 421, in create_plugin_registries
    write_registered_plugins(pkg_dir, plugins, save_type)
  File "/app/geoips_packages/geoips/geoips/create_plugin_registries.py", line 318, in write_registered_plugins
    with open(reg_plug_abspath, "w") as plugin_registry:
PermissionError: [Errno 13] Permission denied: '/app/geoips_packages/overcast-preprocessing/geoips_clavrx/registered_plugins.json'
```

### Checklist for Completion
* [ ]

**Comment by biosafetylvl5** [comment]
Related: #810

**Comment by biosafetylvl5** [comment]
Temporary fix: install all plugins with `-e` or `--user`

**Comment by jsolbrig** [comment]
I think this can be solved by writing our plugin registries to the user's home directory. This means that, if GeoIPS is installed by one user for use by multiple users, the registries would get recreated the first time each user runs GeoIPS, but they would not need access to write to the installation directory anymore. This is bad practice anyways.

After a little research, we can use `platformdirs` to determine the appropriate location for cache files on any operating system. On linux it would be $HOME/.cache, but would be different for other systems. `platformdirs` does correctly handle Linux, OSX, Windows, and WSL.
